project:
  type: website
  output-dir: docs

website:
  title: "mrzknrns"
  navbar:
    left:
      - index.qmd
      - about.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

